### ISSUE TITLE
Исправьте Крым.

### ISSUE THREAD

**Issue by NikeDyachok** [govdesign/map#3]
Прошу исправить Крым, так как он территория Украины.

**Comment by darkboutique** [comment]
При всем уважении, но "Границы и принадлежность территорий на картах отражают текущую позицию России и могут не полностью совпадать с их официальным юридическим статусом."

**Comment by kalloc** [comment]
Но вы можете сделать fork и поправить так, как вам это будет удобно!

**Comment by oxilumin** [comment]
Пишите жалобу в гитхаб, этот репозиторий создан с целью политической пропаганды. Гитхаб не думаю что особо преветствует это. Больше жалоб - больше шанс что забанят.
