### ISSUE TITLE
Crimea is Ukrane 

### ISSUE THREAD

**Issue by KOJJA** [govdesign/map#4]
Remove the Crimea from Russland map

**Comment by kalloc** [comment]
KOJJA: sorry, we do not have permissions to remove Crimea from Russian map

**Comment by kalloc** [comment]
KOJJA: but you can fork and remove!

**Comment by oxilumin** [comment]
Пишите жалобу в гитхаб, этот репозиторий создан с целью политической пропаганды. Гитхаб не думаю что особо преветствует это. Больше жалоб - больше шанс что забанят.
