### ISSUE TITLE
Абхазия и Южная Осетия это Грузия

### ISSUE THREAD

**Issue by Hastalavistababy** [govdesign/map#9]
**Абхазия и Южная Осетия это Грузия !!!!!!!!!!!!!!**

**Comment by ilyago** [comment]
+1

**Comment by giokaxo** [comment]
+1

**Comment by GalayZloy** [comment]
Ребята, хватит спамить! Если вас не устраивает карта, сделайте форк, вам никто не мешает.

**Comment by kalloc** [comment]
Добрый день, эта информация, прежде всего, нужна тем, для кого важно иметь карту, оформленную в соответствии с позицией политики действующего правительства РФ.
